name: perhutaniwisata_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.4.1
  cupertino_icons: ^1.0.2
  bloc: 
  flutter_bloc: 
  equatable: 
  http: 
  firebase_storage: ^11.6.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - img/welcome-1.jpg
    - img/welcome-2.jpg
    - img/welcome-3.jpg
    - img/perhutanilogo.png
    - img/welcome4.jpg
    - img/welcome5.jpg
    - img/welcome6.jpg
    - img/startbutton50.png
    - img/loginbutton.png
    - img/loginbutton2.png
    - img/start1.png
    - img/start2.png
    - img/start3.png
    - img/bukit.jpeg
    - img/danau.jpg
    - img/hutan_wisata.jpeg
    - img/curug_bajing.jpeg
    - img/startbutton.png
    - img/startbutton3.png
    - img/arrow.png
    - img/arrowwhite.png
    - img/rightarrow.png
    - img/rightarrow.svg
    - img/rightarrowwhite.png
    - img/google.png

  fonts:
    - family: SoundOfNature
      fonts:
        - asset: fonts/Sound Of Nature.ttf
    - family: StoryOfNature
      fonts:
        - asset: fonts/Story Of Nature.ttf
