// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTLiV_cfiJhrLnxQF4v91Ce7R-y8nMkY',
    appId: '1:895303786091:web:ae43fd26d9b7539c90db2e',
    messagingSenderId: '895303786091',
    projectId: 'flutter-ekowisata-app',
    authDomain: 'flutter-ekowisata-app.firebaseapp.com',
    storageBucket: 'flutter-ekowisata-app.appspot.com',
    measurementId: 'G-EPCV7016VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa99WTuVrq6Qs0_sv9PG39NE4RxyepwGY',
    appId: '1:895303786091:android:ace7f7b59fe2f06e90db2e',
    messagingSenderId: '895303786091',
    projectId: 'flutter-ekowisata-app',
    storageBucket: 'flutter-ekowisata-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgKIqjCvisPFgNxYdINIadoVKgQ6_9ts',
    appId: '1:895303786091:ios:fe8c3588b0798b2290db2e',
    messagingSenderId: '895303786091',
    projectId: 'flutter-ekowisata-app',
    storageBucket: 'flutter-ekowisata-app.appspot.com',
    iosBundleId: 'com.example.perhutaniwisataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfgKIqjCvisPFgNxYdINIadoVKgQ6_9ts',
    appId: '1:895303786091:ios:fe8c3588b0798b2290db2e',
    messagingSenderId: '895303786091',
    projectId: 'flutter-ekowisata-app',
    storageBucket: 'flutter-ekowisata-app.appspot.com',
    iosBundleId: 'com.example.perhutaniwisataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuTLiV_cfiJhrLnxQF4v91Ce7R-y8nMkY',
    appId: '1:895303786091:web:71e874901ac3181590db2e',
    messagingSenderId: '895303786091',
    projectId: 'flutter-ekowisata-app',
    authDomain: 'flutter-ekowisata-app.firebaseapp.com',
    storageBucket: 'flutter-ekowisata-app.appspot.com',
    measurementId: 'G-7C6GCG52M9',
  );
}
